/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minimart.Forms;

import com.minimart.BUS.NhanVienBUS;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Pero
 */
public class Login_Form extends javax.swing.JFrame {

    private final Timer timerUp;

    /**
     * Creates new form Login_Form
     */
    public Login_Form() {
        //Set Timer
        this.timerUp = new Timer(3, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(jpanel_warning.getHeight() != 0)
                {
                    jpanel_warning.setBounds(jpanel_warning.getX(), jpanel_warning.getY(), jpanel_warning.getWidth()
                            , jpanel_warning.getHeight() -5);
                }else{
                    timerUp.stop();
                }
            }
        });
        
        initComponents();
        
        //Center this form
        this.setLocationRelativeTo(null);
        
        //Set Icon
        background_login.setIcon(new javax.swing.ImageIcon("./IMAGES/Background.png"));
        icon_pass.setIcon(new javax.swing.ImageIcon("./IMAGES/login_pass.png"));
        icon_user.setIcon(new javax.swing.ImageIcon("./IMAGES/login_user.png"));
        icon_close.setIcon(new javax.swing.ImageIcon("./IMAGES/login_close.png"));
        icon_warning_close.setIcon(new javax.swing.ImageIcon("./IMAGES/login_closewarning.png"));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background_login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Login_button = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        icon_close = new javax.swing.JLabel();
        login_user_panel = new javax.swing.JPanel();
        text_username = new javax.swing.JTextField();
        icon_user = new javax.swing.JLabel();
        login_pass_panel = new javax.swing.JPanel();
        icon_pass = new javax.swing.JLabel();
        text_pass = new javax.swing.JPasswordField();
        jpanel_warning = new javax.swing.JPanel();
        warning_message = new javax.swing.JLabel();
        icon_warning_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 248, 254));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        background_login.setBackground(new java.awt.Color(255, 153, 153));
        background_login.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Myriad Pro Black SemiCond", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(111, 7, 165));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login here!");

        Login_button.setBackground(new java.awt.Color(57, 13, 93));
        Login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_buttonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("iCiel Gotham Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 104, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign In");

        javax.swing.GroupLayout Login_buttonLayout = new javax.swing.GroupLayout(Login_button);
        Login_button.setLayout(Login_buttonLayout);
        Login_buttonLayout.setHorizontalGroup(
            Login_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        Login_buttonLayout.setVerticalGroup(
            Login_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jCheckBox1.setBackground(new java.awt.Color(255, 248, 254));
        jCheckBox1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setText("Keep me sign in");
        jCheckBox1.setBorder(null);

        icon_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_closeMouseClicked(evt);
            }
        });

        login_user_panel.setBackground(new java.awt.Color(221, 220, 220));

        text_username.setBackground(new java.awt.Color(221, 220, 220));
        text_username.setFont(new java.awt.Font("iCiel Gotham Medium", 0, 18)); // NOI18N
        text_username.setForeground(new java.awt.Color(51, 51, 51));
        text_username.setBorder(null);

        javax.swing.GroupLayout login_user_panelLayout = new javax.swing.GroupLayout(login_user_panel);
        login_user_panel.setLayout(login_user_panelLayout);
        login_user_panelLayout.setHorizontalGroup(
            login_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_user_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_user, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_username, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        login_user_panelLayout.setVerticalGroup(
            login_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_user_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(login_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        login_pass_panel.setBackground(new java.awt.Color(221, 220, 220));

        text_pass.setBackground(new java.awt.Color(221, 220, 220));
        text_pass.setFont(new java.awt.Font("iCiel Gotham Medium", 0, 18)); // NOI18N
        text_pass.setForeground(new java.awt.Color(51, 51, 51));
        text_pass.setBorder(null);

        javax.swing.GroupLayout login_pass_panelLayout = new javax.swing.GroupLayout(login_pass_panel);
        login_pass_panel.setLayout(login_pass_panelLayout);
        login_pass_panelLayout.setHorizontalGroup(
            login_pass_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_pass_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        login_pass_panelLayout.setVerticalGroup(
            login_pass_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_pass_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(login_pass_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icon_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(text_pass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanel_warning.setBackground(new java.awt.Color(255, 51, 51));

        warning_message.setFont(new java.awt.Font("iCiel Gotham Medium", 0, 20)); // NOI18N
        warning_message.setForeground(new java.awt.Color(255, 255, 255));
        warning_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warning_message.setAlignmentY(2.0F);
        warning_message.setPreferredSize(new java.awt.Dimension(70, 345));

        icon_warning_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_warning_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_warning_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpanel_warningLayout = new javax.swing.GroupLayout(jpanel_warning);
        jpanel_warning.setLayout(jpanel_warningLayout);
        jpanel_warningLayout.setHorizontalGroup(
            jpanel_warningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_warningLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(warning_message, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_warning_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jpanel_warningLayout.setVerticalGroup(
            jpanel_warningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_warningLayout.createSequentialGroup()
                .addGroup(jpanel_warningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_warning_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_warningLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(warning_message, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(background_login, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(login_user_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50))
                                .addComponent(login_pass_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jpanel_warning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icon_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(icon_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(login_user_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_pass_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(28, 28, 28)
                .addComponent(Login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jpanel_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background_login, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Timer to show the warning
    Timer timerDown = new Timer(10, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(jpanel_warning.getHeight() != 80)
            {
                jpanel_warning.setBounds(jpanel_warning.getX(), jpanel_warning.getY(), jpanel_warning.getWidth()
                        , jpanel_warning.getHeight() + 5);
            }else{
                timerDown.stop();
            }
        }
    });
    private void icon_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_icon_closeMouseClicked

    private void Login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_buttonMouseClicked
        String username = text_username.getText().trim();
        String password = String.valueOf(text_pass.getPassword());
        NhanVienBUS nhanVienBus=new NhanVienBUS();
        int bool=nhanVienBus.login(username,password);
        if(username.equals(""))
        {
            warning_message.setText("Enter your username!");
        }
        else if (password.equals(""))
        {
            warning_message.setText("Enter your password!");
        }
        else if (bool==1 )
        {
            this.dispose();
            Dashboard_Form  dashboard1 = new Dashboard_Form();
            dashboard1.setVisible(true);
        }
        else if (bool == 0)
        {
            this.dispose();
            POS pos1 = new POS();
            pos1.setVisible(true);
        }
        else
        {
            warning_message.setText("Invalid username or password!");
        }
        //show the warning message
        timerDown.start();
    }//GEN-LAST:event_Login_buttonMouseClicked

    private void Login_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_buttonMouseEntered
        Login_button.setBackground(new java.awt.Color(75,18,120));
    }//GEN-LAST:event_Login_buttonMouseEntered

    private void Login_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_buttonMouseExited
        Login_button.setBackground(new java.awt.Color(53,22,77));
    }//GEN-LAST:event_Login_buttonMouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        Login_button.setBackground(new java.awt.Color(36,14,54));
    }//GEN-LAST:event_jPanel1MousePressed

    private void icon_warning_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_warning_closeMouseClicked
        //hide the warning
        timerUp.start();
    }//GEN-LAST:event_icon_warning_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login_button;
    private javax.swing.JLabel background_login;
    private javax.swing.JLabel icon_close;
    private javax.swing.JLabel icon_pass;
    private javax.swing.JLabel icon_user;
    private javax.swing.JLabel icon_warning_close;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpanel_warning;
    private javax.swing.JPanel login_pass_panel;
    private javax.swing.JPanel login_user_panel;
    private javax.swing.JPasswordField text_pass;
    private javax.swing.JTextField text_username;
    private javax.swing.JLabel warning_message;
    // End of variables declaration//GEN-END:variables
}